# Generated by Django 5.2 on 2025-05-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
